# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-24 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='\u6807\u9898')),
                ('content', models.TextField(verbose_name='\u5185\u5bb9')),
                ('rcount', models.IntegerField(default=0, verbose_name='\u9605\u8bfb\u91cf')),
                ('coms', models.IntegerField(default=0, verbose_name='\u8bc4\u8bba\u6570')),
                ('like', models.IntegerField(default=0, verbose_name='\u70b9\u8d5e\u6570')),
                ('ctime', models.DateTimeField(auto_now_add=True, max_length=30, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('utime', models.DateTimeField(auto_now=True, max_length=30, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('tops', models.IntegerField(choices=[(1, '\u662f'), (0, '\u5426')], default=0, verbose_name='\u7f6e\u9876')),
            ],
            options={
                'db_table': 'user_blogs',
                'verbose_name': '\u535a\u5ba2',
                'verbose_name_plural': '\u535a\u5ba2',
            },
        ),
        migrations.CreateModel(
            name='Bmarks',
            fields=[
                ('id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('tags', models.CharField(max_length=128, unique=True, verbose_name='\u6807\u7b7e')),
            ],
            options={
                'db_table': 'blog_marks',
                'verbose_name': '\u5206\u7c7b',
                'verbose_name_plural': '\u5206\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('cbid', models.IntegerField(null=True, verbose_name='\u535a\u5ba2id')),
                ('cblog', models.CharField(max_length=128, null=True, verbose_name='\u535a\u5ba2\u6807\u9898')),
                ('comms', models.TextField(max_length=300, verbose_name='\u8bc4\u8bba\u5185\u5bb9')),
                ('uses', models.CharField(default='\u533f\u540d', max_length=128, verbose_name='\u8bc4\u8bba\u4eba')),
                ('ctime', models.DateTimeField(auto_now_add=True, max_length=30, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'db_table': 'use_comments',
                'verbose_name': '\u8bc4\u8bba',
                'verbose_name_plural': '\u8bc4\u8bba',
            },
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('like_user', models.CharField(default='\u533f\u540d', max_length=128, verbose_name='\u70b9\u8d5e\u4eba')),
                ('like_title', models.CharField(max_length=128, verbose_name='\u88ab\u8d5e\u6587\u7ae0')),
                ('like_id', models.IntegerField(null=True, verbose_name='\u88ab\u8d5e\u6587\u7ae0id')),
                ('like_time', models.DateTimeField(auto_now_add=True, max_length=30, verbose_name='\u70b9\u8d5e\u65f6\u95f4')),
            ],
            options={
                'db_table': 'blog_like',
                'verbose_name': '\u70b9\u8d5e',
                'verbose_name_plural': '\u70b9\u8d5e',
            },
        ),
        migrations.AlterUniqueTogether(
            name='bmarks',
            unique_together=set([('tags',)]),
        ),
        migrations.AddField(
            model_name='blogs',
            name='marks',
            field=models.ForeignKey(default='\u672a\u5206\u7c7b', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='blog_marks', to='blog.Bmarks', to_field='tags', verbose_name='\u5206\u7c7b'),
        ),
    ]
