# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-18 23:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128, unique=True)),
                ('content', models.TextField()),
                ('rcount', models.IntegerField(default=0)),
                ('coms', models.IntegerField(default=0)),
                ('ctime', models.DateTimeField(auto_now_add=True, max_length=30)),
                ('utime', models.DateTimeField(auto_now=True, max_length=30)),
            ],
            options={
                'db_table': 'user_blogs',
                'verbose_name': '\u535a\u5ba2',
                'verbose_name_plural': '\u535a\u5ba2',
            },
        ),
        migrations.CreateModel(
            name='Bmarks',
            fields=[
                ('id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('tags', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'db_table': 'blog_marks',
                'verbose_name': '\u5206\u7c7b',
                'verbose_name_plural': '\u5206\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('comms', models.TextField(max_length=300)),
                ('uses', models.CharField(default='\u533f\u540d', max_length=128)),
                ('cbid', models.IntegerField(null=True)),
                ('cblog', models.CharField(max_length=128, null=True)),
                ('ctime', models.DateTimeField(auto_now_add=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'use_comments',
            },
        ),
        migrations.AlterUniqueTogether(
            name='bmarks',
            unique_together=set([('tags',)]),
        ),
        migrations.AddField(
            model_name='blogs',
            name='marks',
            field=models.ForeignKey(default='\u672a\u5206\u7c7b', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='blog_marks', to='blog.Bmarks', to_field='tags'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='uname',
            field=models.ForeignKey(default='\u533f\u540d', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='auth_user', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterUniqueTogether(
            name='blogs',
            unique_together=set([('title',)]),
        ),
    ]
