# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-21 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('like_user', models.CharField(default='\u533f\u540d', max_length=128)),
                ('like_title', models.CharField(max_length=128, unique=True)),
                ('like_id', models.IntegerField(null=True)),
                ('like_time', models.DateTimeField(auto_now_add=True, max_length=30)),
            ],
            options={
                'db_table': 'blog_like',
            },
        ),
        migrations.AddField(
            model_name='blogs',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
