# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-24 10:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='uname',
            field=models.ForeignKey(default='\u533f\u540d', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='\u7528\u6237\u540d'),
        ),
        migrations.AlterUniqueTogether(
            name='blogs',
            unique_together=set([('title',)]),
        ),
    ]
