# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-21 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180821_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='like_title',
            field=models.CharField(max_length=128),
        ),
    ]
