# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-03 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190124_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True, max_length=30, null=True, verbose_name='\u8bc4\u8bba\u65f6\u95f4'),
        ),
    ]
