# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-28 12:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180821_1937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': '\u8bc4\u8bba', 'verbose_name_plural': '\u8bc4\u8bba'},
        ),
        migrations.AlterModelOptions(
            name='likes',
            options={'verbose_name': '\u70b9\u8d5e', 'verbose_name_plural': '\u70b9\u8d5e'},
        ),
        migrations.AlterField(
            model_name='blogs',
            name='coms',
            field=models.IntegerField(default=0, verbose_name='\u8bc4\u8bba\u6570'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='content',
            field=models.TextField(verbose_name='\u5185\u5bb9'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True, max_length=30, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='like',
            field=models.IntegerField(default=0, verbose_name='\u70b9\u8d5e\u6570'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='marks',
            field=models.ForeignKey(default='\u672a\u5206\u7c7b', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='blog_marks', to='blog.Bmarks', to_field='tags', verbose_name='\u5206\u7c7b'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='rcount',
            field=models.IntegerField(default=0, verbose_name='\u9605\u8bfb\u91cf'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='title',
            field=models.CharField(max_length=128, unique=True, verbose_name='\u6807\u9898'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='uname',
            field=models.ForeignKey(default='\u533f\u540d', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='auth_user', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='\u7528\u6237\u540d'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='utime',
            field=models.DateTimeField(auto_now=True, max_length=30, verbose_name='\u4fee\u6539\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='bmarks',
            name='tags',
            field=models.CharField(max_length=128, unique=True, verbose_name='\u6807\u7b7e'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='cbid',
            field=models.IntegerField(null=True, verbose_name='\u535a\u5ba2id'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='cblog',
            field=models.CharField(max_length=128, null=True, verbose_name='\u535a\u5ba2\u6807\u9898'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comms',
            field=models.TextField(max_length=300, verbose_name='\u8bc4\u8bba\u5185\u5bb9'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True, max_length=30, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='uses',
            field=models.CharField(default='\u533f\u540d', max_length=128, verbose_name='\u8bc4\u8bba\u4eba'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='like_id',
            field=models.IntegerField(null=True, verbose_name='\u88ab\u8d5e\u6587\u7ae0id'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='like_time',
            field=models.DateTimeField(auto_now_add=True, max_length=30, verbose_name='\u70b9\u8d5e\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='like_title',
            field=models.CharField(max_length=128, verbose_name='\u88ab\u8d5e\u6587\u7ae0'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='like_user',
            field=models.CharField(default='\u533f\u540d', max_length=128, verbose_name='\u70b9\u8d5e\u4eba'),
        ),
    ]
