# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-31 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181229_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateTimeField(blank=True, default='2018-01-01', null=True, verbose_name='\u751f\u65e5'),
        ),
    ]
