# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-14 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181231_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='tops',
            field=models.IntegerField(choices=[('1', '\u662f'), ('0', '\u5426')], default=0, verbose_name='\u7f6e\u9876'),
        ),
    ]
