# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-14 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogs_tops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='tops',
            field=models.IntegerField(choices=[(1, '\u662f'), (0, '\u5426')], default=0, verbose_name='\u7f6e\u9876'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='user',
            name='head_img',
            field=models.CharField(max_length=255, null=True, verbose_name='\u5934\u50cf'),
        ),
    ]
