# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-14 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190114_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='user',
            name='head_img',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5934\u50cf'),
        ),
    ]
