# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-29 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='head_img',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='\u5934\u50cf'),
        ),
    ]
