# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-03 10:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0002_auto_20190126_1652'),
        ('center', '0002_auto_20190129_1125'),
    ]

    operations = [
    ]
